### ISSUE TITLE
Pi-Sugar 2 programmable button doesn't work

### ISSUE THREAD

**Issue by larrylisky** [PiSugar/pisugar-power-manager-rs#19]
I did some debugging in 'pisugar-core.rs' and 'ip5902.rs' and found that [this code block](https://github.com/PiSugar/pisugar-power-manager-rs/blob/9d30e4d21d10d4ef04c530d92324448ca2f4ebd5/pisugar-core/src/ip5209.rs#L394) seems to be the problem.  If I swap the two gpio_value &... lines, the button began to work.  I don' know if the 'if statement' itself is at fault, or the return values are in the wrong place..., but something is swapped.

**Comment by fengyc** [comment]
@larrylisky It looks like the `model` parameter is incorrect. 

See `/etc/default/pisugar-server.default`, replace `--model 'PiSugar 2 (4-LEDs)'` with `--model 'PiSugar 2 (2-LEDs)'`.

**Comment by larrylisky** [comment]
Thank you!  This worked.
