### ISSUE TITLE
[FEATURE] Install the package without prompt/user interaction (PiSugar 2 Pro)

### ISSUE THREAD

**Issue by cariacou** [PiSugar/pisugar-power-manager-rs#42]
Right now, installing the package requires the user to manually select the PiSugar 2 Pro version.

Is it possible to modify the installation script to provide an installation without any user interaction? I am planning on using this on a large scale development

**Comment by fengyc** [comment]
@cariacou Sure, `debconf-set-selections` should help, please refer to the doc https://manpages.debian.org/bullseye/debconf/debconf-set-selections.1.en.html

**Comment by fengyc** [comment]
@cariacou I will close the issue as there is not more comments, if you still have questions, please feel free to reopen it.
