### ISSUE TITLE
Rustup installation failure at installing rustc component in Pi Zero W

### ISSUE THREAD

**Issue by FGMGIT** [PiSugar/pisugar-power-manager-rs#6]
installing component 'rustc'
31.1 MiB / 49.3 MiB ( 63 %) 1.2 MiB/s in 38s ETA: 14smemory allocation of 146176856 bytes failedAborted

SOLUTION:
rust-lang/rustup#2128

**Comment by fengyc** [comment]
@FGMGIT It takes a lot of time to compile the project in Pi Zero W. For that reason, compiling in Pi zero is not recommended. I had documented the cross compiling steps in README, please feel free to open an issue if you are stuck with any problem.

**Comment by FGMGIT** [comment]
Dear @fengyc can you give some help, I'm stucked with the rust installation for PiSugar 2. No way from PiZero W nor from cross compiling on macOS Catalina:

PiZero:

<img width="886" alt="Captura de pantalla 2020-05-24 a las 19 12 06" src="https://user-images.githubusercontent.com/15965708/82760239-9410d900-9df2-11ea-8574-cca7cc3ed2a2.png">

macOS:

<img width="894" alt="Captura de pantalla 2020-05-24 a las 19 12 18" src="https://user-images.githubusercontent.com/15965708/82760276-c9b5c200-9df2-11ea-9e8e-652bfa467a5e.png">

**Comment by fengyc** [comment]
@FGMGIT You need to clone the git project and change the current working directory to the project root directory.

**Comment by FGMGIT** [comment]
**warning: spurious network error**
I'm not under proxi, firewall, etc.

<img width="856" alt="Captura de pantalla 2020-05-26 a las 18 20 57" src="https://user-images.githubusercontent.com/15965708/82925489-0b26a880-9f7e-11ea-897b-093873400e26.png">

**Comment by fengyc** [comment]
Comment out or remove this line https://github.com/PiSugar/pisugar-power-manager-rs/blob/f1b1c11d18adb23b5a2282b479f0ed7d13201dae/.cargo/config#L3

**Comment by FGMGIT** [comment]
**Build fails compiling pisugar-poweroff error: linker `arm-linux-musleabihf-ld` not found**

<img width="707" alt="Captura de pantalla 2020-06-02 a las 12 22 52" src="https://user-images.githubusercontent.com/15965708/83509695-1de43480-a4cc-11ea-82e2-360d8d93a106.png">

**Comment by fengyc** [comment]
The cargo build default target has been changed to `arm-unknown-linux-musleabihf`.  If you want to compile the source code in rapi, remove the following lines: https://github.com/PiSugar/pisugar-power-manager-rs/blob/76dbc4769e6d2abe8979dbcec54c4171e68a0fd8/.cargo/config#L8-L9

**Comment by richardanaya** [comment]
I was able to install 1.44.1 using RUSTUP_UNPACK_RAM=200000000 fore rustup install

**Comment by fengyc** [comment]
There is no more updates recently, I will close the issue soon. Feel free to reopen it if there are more questions.
