### ISSUE TITLE
PiZero W reboot loop when load pisugar-poweroff.service

### ISSUE THREAD

**Issue by FGMGIT** [PiSugar/pisugar-power-manager-rs#7]
PiZero W reboot loop when load pisugar-poweroff.service on boot process. How can I stop that service if i can't boot the PiZero?

**Comment by fengyc** [comment]
The pisugar-poweroff service runs once only before poweroff. I could not reproduce the error, please provide detailed steps to reproduce. 

And please connect pizero to a monitor and see what's happening, might be something else blocks the boot procedure.

**Comment by FGMGIT** [comment]
Yes it was when the system load pisugar-poweroff.service and reboot again and again. Solved powering off manually from the switch.

**Comment by fengyc** [comment]
@FGMGIT Is the issue still exists in the latest build? Download the latest build from url: https://github.com/PiSugar/pisugar-power-manager-rs/releases/download/latest/pisugar-poweroff_1.4.2_armhf.deb

**Comment by fengyc** [comment]
There is no more updates recently, I will close the issue soon. Feel free to reopen it if there are more questions.
